name: sweet_cookie_jar
description: A most easily usable cookie management library in Dart. With SweetCookieJar, you can easily manage cookie on your application.
version: 1.1.1
homepage: https://github.com/myConsciousness/sweet-cookie-jar

environment:
  sdk: ^3.0.0

dependencies:
  collection: ^1.17.2
  http: ^1.1.0
  universal_io: ^2.2.2

dev_dependencies:
  flutter_lints: ^2.0.2
  test: ^1.24.4
  import_sorter: ^4.6.0
